#!/bin/sh

# Helper script to build Python source files from gRPC/protobuf spec
#
# This is not intended to be run manually except for testing purposes,
# in which case it should be run from within the root directory of the
# project repository.

set -ex

protos="$(find ./proto -type f -name "*.proto")"

# shellcheck disable=SC2086
python -m grpc_tools.protoc \
    -I proto \
    -I submodules/api-common-protos \
    --python_out=py \
    --grpc_python_out=py \
    --mypy_out=py \
    --mypy_grpc_out=py \
    ${protos}
