# GitHub issue form. For more information see:
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: Request a feature or enhancement ✨
description: Use this if something is missing or could be done better or easier.
labels: part:❓, priority:❓, type:enhancement
body:
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to fill out this feature or enhancement
        request!
  - type: textarea
    id: whats-needed
    attributes:
      label: What's needed?
      description:
        Please tell us what's missing or what could be done better or easier.
      placeholder: What's missing or what could be done better or easier.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description:
        Please tell us how do you think the needs above can be fulfilled. Only
        fill this field if it wasn't described above.
      placeholder:
        How do you think the needs above can be fulfilled. Only fill this field
        if it wasn't described above.
  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description:
        Please tell us about the main use cases you see for this new feature or
        enhancement to help us understand more.
      placeholder:
        The main use cases you see for this new feature or enhancement to help
        us understand more.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives and workarounds
      description:
        Please tell us if you tried any alternatives or workarounds for those
        use cases and how (un)useful they are.
      placeholder:
        Any alternatives or workarounds for those use cases and how (un)useful
        they are.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description:
        Please add any addition information here, screenshots, diagrams, etc.
      placeholder: Any addition information here, screenshots, diagrams, etc.
